sudo: required
services: docker
jdk: oraclejdk8
language: groovy

before_install:
  - openssl aes-256-cbc -K $encrypted_bcbb3ed29368_key -iv $encrypted_bcbb3ed29368_iv -in gradle.properties.enc -out gradle.properties -d
  - curl -L https://github.com/docker/compose/releases/download/1.5.1/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker -v
  # https://github.com/travis-ci/travis-ci/issues/4778
  - sudo iptables -n --list "DOCKER" >/dev/null 2>&1 || sudo iptables -N DOCKER

install: ./installViaTravis.sh
script: ./buildViaTravis.sh
