sudo: required
services: 
  - docker
jdk: oraclejdk8
language: groovy

branches:
  except:
  - /^tmp-.*$/

before_install:
  - openssl aes-256-cbc -K $encrypted_f3d5ce600e4d_key -iv $encrypted_f3d5ce600e4d_iv -in gradle.properties.enc -out gradle.properties -d
  - docker -v
  - docker-compose -v

install: ./installViaTravis.sh
script: ./buildViaTravis.sh
